#!/bin/sh

if [ $(id -u) -ne 0 ]; then
	echo "Please run as root"
	exit 1
fi

do_build() {
	cd "$1"
	make CMAKE_BUILD_TYPE=Release
	strip build/bin/nvim
	make install
	cd ..
}

if [ "$1" = "-g" ]; then
	git clone 'https://github.com/neovim/neovim'
	do_build neovim
	rm -rf neovim
else
	wget --no-check-certificate --content-disposition \
		"https://github.com/neovim/neovim/tarball/nightly" \
		-O neovim-nightly.tar.gz
	tar -xvf neovim-nightly.tar.gz --strip-components 1 --one-top-level
	do_build neovim-nightly
	rm -rf neovim-nightly neovim-nightly.tar.gz
fi
